In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('demo_36r1h.csv')

In [3]:
df

,commonscripcode,Client_code,L4Client_Code,cltname,shortname,qty,avgcost,cost,mktvalue,mktvalue1,...,FolioNo,InceptionDate,mktrate,netgain,portfolioWtg,xirr_asset,benchmarkxirr_asset,Classification,issuer,maturitydate
0,9785,3.0,95.0,SURESH KISHANLAL MUNDRA,Interest Receivable on Bond / GSec - Not Due,0.000,0.000000e+00,55433.99,55433.99,28666458.87,...,NaN,1900-01-01,0.00,0.00,0.19,2.997058,0.000000,Equity: Flexi Cap,NaN,NaN
1,9785,3.0,101.0,SURESH KISHANLAL MUNDRA,Interest Receivable on Bond / GSec - Not Due,0.000,0.000000e+00,-1.36,-1.36,28666458.87,...,NaN,1900-01-01,0.00,0.00,0.00,2.997058,0.000000,Equity: Flexi Cap,NaN,NaN
2,9785,3.0,3.0,SURESH KISHANLAL MUNDRA,Interest Receivable on Bond / GSec - Not Due,0.000,0.000000e+00,251297.15,251297.15,28666458.87,...,NaN,1900-01-01,0.00,0.00,0.88,2.997058,0.000000,Equity: Flexi Cap,NaN,NaN
3,9785,3.0,4.0,SURESH KISHANLAL MUNDRA,Interest Receivable on Bond / GSec - Not Due,0.000,0.000000e+00,263175.86,263175.86,28666458.87,...,NaN,1900-01-01,0.00,0.00,0.92,2.997058,0.000000,Equity: Flexi Cap,NaN,NaN
4,9785,3.0,7548.0,SURESH KISHANLAL MUNDRA,Interest Receivable on Bond / GSec - Not Due,0.000,0.000000e+00,36597.60,36597.60,28666458.87,...,NaN,1900-01-01,0.00,0.00,0.13,2.997058,0.000000,Equity: Flexi Cap,NaN,NaN
5,329,3.0,101.0,SURESH KISHANLAL MUNDRA,IPO Application,0.000,0.000000e+00,0.00,0.00,28666458.87,...,NaN,1900-01-01,0.00,0.00,0.00,2.997058,0.000000,NaN,NaN,NaN
6,329,3.0,95.0,SURESH KISHANLAL MUNDRA,IPO Application,0.000,0.000000e+00,0.00,0.00,28666458.87,...,NaN,1900-01-01,0.00,0.00,0.00,2.997058,0.000000,NaN,NaN,NaN
7,329,3.0,4.0,SURESH KISHANLAL MUNDRA,IPO Application,0.000,0.000000e+00,0.00,0.00,28666458.87,...,NaN,1900-01-01,0.00,0.00,0.00,2.997058,0.000000,NaN,NaN,NaN
8,329,3.0,3.0,SURESH KISHANLAL MUNDRA,IPO Application,0.000,0.000000e+00,0.00,0.00,28666458.87,...,NaN,1900-01-01,0.00,0.00,0.00,2.997058,0.000000,NaN,NaN,NaN
9,731,3.0,3.0,SURESH KISHANLAL MUNDRA,CFSL MLD SR 41 A (INE244R07843) 04-AUG-2022 - ...,25.000,1.003000e+05,2507500.00,3669172.25,28666458.87,...,NaN,1900-01-01,146766.89,1161672.25,12.80,12.568255,10.211189,NaN,NaN,NaN
10,778,3.0,3.0,SURESH KISHANLAL MUNDRA,CFSL MLD SR 43 C(INE244R07868) 01-NOV-2022 - M...,25.000,1.003500e+05,2508750.00,4096475.25,28666458.87,...,NaN,1900-01-01,163859.01,1587725.25,14.29,12.568255,10.211189,NaN,NaN,NaN
11,985,3.0,3.0,SURESH KISHANLAL MUNDRA,CFSL MLD SR 53 C (INE244R07AC3) 16-DEC-2022 - ...,25.000,1.010900e+05,2527250.00,2892776.25,28666458.87,...,NaN,1900-01-01,115711.05,365526.25,10.09,12.568255,10.211189,NaN,NaN,NaN
12,62346,3.0,95.0,SURESH KISHANLAL MUNDRA,Aditya Birla SL Credit Risk - Segregated Portf...,25444.793,0.000000e+00,0.00,4142.41,28666458.87,...,1.036211e+09,1900-01-01,0.16,4142.41,0.01,0.000000,0.000000,Debt: Credit Risk,Aditya Birla Sun Life Mutual Fund,NaN
13,62346,3.0,3.0,SURESH KISHANLAL MUNDRA,Aditya Birla SL Credit Risk - Segregated Portf...,43042.543,0.000000e+00,0.00,7007.33,28666458.87,...,1.036211e+09,1900-01-01,0.16,7007.33,0.02,0.000000,0.000000,Debt: Credit Risk,Aditya Birla Sun Life Mutual Fund,NaN
14,63881,3.0,3.0,SURESH KISHANLAL MUNDRA,BHARAT Bond ETF FOF - April 2032 Reg-G,250516.090,9.978900e+00,2499875.01,2442807.45,28666458.87,...,9.103882e+09,1900-01-01,9.75,-57067.56,8.52,0.000000,0.000000,Other: FoFs (Overseas/Domestic),Edelweiss Mutual Fund,NaN
15,62421,3.0,3.0,SURESH KISHANLAL MUNDRA,BHARAT Bond FOF - April 2030 Reg-G,250000.000,1.000000e+01,2500000.00,2922450.00,28666458.87,...,9.103882e+09,1900-01-01,11.69,422450.00,10.19,0.000000,0.000000,Other: FoFs (Overseas/Domestic),Edelweiss Mutual Fund,NaN
16,9887,3.0,3.0,SURESH KISHANLAL MUNDRA,Nippon India ETF Liquid BeES-IDCWD,0.536,1.000000e+03,536.00,536.00,28666458.87,...,3.000000e+00,1900-01-01,1000.00,30.45,0.00,0.000000,0.000000,Other: Index Funds / ETFs,Nippon India Mutual Fund,NaN
17,424,3.0,3.0,SURESH KISHANLAL MUNDRA,8.71 [INE020B07HS2] REC TAX FREE BOND 2013 Tr...,1000.000,1.000000e+03,1000000.00,1172500.00,28666458.87,...,NaN,1900-01-01,1172.50,933731.16,4.09,9.710514,8.172308,Non-Convertible Debenture,NaN,1900-01-01
18,424,3.0,95.0,SURESH KISHANLAL MUNDRA,8.71 [INE020B07HS2] REC TAX FREE BOND 2013 Tr...,1000.000,1.000000e+03,1000000.00,1172500.00,28666458.87,...,NaN,1900-01-01,1172.50,933731.16,4.09,9.710514,8.172308,Non-Convertible Debenture,NaN,1900-01-01
19,1483,3.0,3.0,SURESH KISHANLAL MUNDRA,HUDCO 2016 [INE031A07AT4] Tranche II Series 2B...,521.000,1.000000e+03,521000.00,600452.50,28666458.87,...,NaN,1900-01-01,1152.50,330496.46,2.09,9.710514,8.172308,Non-Convertible Debenture,NaN,1900-01-01
20,463,3.0,7548.0,SURESH KISHANLAL MUNDRA,HUDCO INE031A07949 Tax Free T1 - S2B - CIV For...,100.000,1.000000e+03,100000.00,117920.00,28666458.87,...,NaN,1900-01-01,1179.20,93708.76,0.41,9.710514,8.172308,Non-Convertible Debenture,NaN,1900-01-01
21,121,3.0,3.0,SURESH KISHANLAL MUNDRA,HUDCO Tax Free Bond SR2(INE031A07840 Category ...,2000.000,9.870000e+02,1974000.00,2255000.00,28666458.87,...,NaN,1900-01-01,1127.50,1952012.04,7.87,9.710514,8.172308,Non-Convertible Debenture,NaN,1900-01-01
22,673,3.0,7548.0,SURESH KISHANLAL MUNDRA,IRFC [INE053F07744] TAX FREE T2 S2B C4 for 15 ...,400.000,1.000000e+03,400000.00,476040.00,28666458.87,...,NaN,1900-01-01,1190.10,368580.92,1.66,9.710514,8.172308,Non-Convertible Debenture,NaN,1900-01-01
23,92,3.0,4.0,SURESH KISHANLAL MUNDRA,NHAI Tax Free Series II (8.30%) (INE906B07CB9),1173.000,1.000000e+03,1173000.00,1349184.60,28666458.87,...,NaN,1900-01-01,1150.20,1188813.00,4.71,9.710514,8.172308,Non-Convertible Debenture,NaN,1900-01-01
24,491,3.0,3.0,SURESH KISHANLAL MUNDRA,PFC (INE134E07463) Tax Free@ 8.92 % 20 yrs Tr1...,1000.000,1.000000e+03,1000000.00,1321200.00,28666458.87,...,NaN,1900-01-01,1321.20,1087581.32,4.61,9.710514,8.172308,Non-Convertible Debenture,NaN,1900-01-01
25,106,3.0,4.0,SURESH KISHANLAL MUNDRA,PFC Tax Free Bonds Option II (8.30%) (INE134E0...,1402.000,1.000000e+03,1402000.00,1605149.80,28666458.87,...,NaN,1900-01-01,1144.90,1410898.95,5.60,9.710514,8.172308,Non-Convertible Debenture,NaN,1900-01-01
26,647,3.0,95.0,SURESH KISHANLAL MUNDRA,REC [INE020B07IH3] TAX FREE T2 S3B C4 for 20 Y...,250.000,1.000000e+03,250000.00,350350.00,28666458.87,...,NaN,1900-01-01,1401.40,282879.68,1.22,9.710514,8.172308,Non-Convertible Debenture,NaN,1900-01-01
27,45,3.0,3.0,SURESH KISHANLAL MUNDRA,United Phosphorus Limited NCD @ 10.70% (INE628...,1.000,1.021400e+06,1021400.00,1007200.00,28666458.87,...,NaN,1900-01-01,1007200.00,1123222.70,3.51,9.710514,8.172308,Non-Convertible Debenture,NaN,1900-01-01
28,3545,3.0,95.0,SURESH KISHANLAL MUNDRA,INDRAYANI BIOTECH LTD,12.000,8.000000e+00,96.00,474.00,28666458.87,...,NaN,1900-01-01,39.50,378.00,0.00,-4.530036,11.880596,Floriculture,NaN,NaN
29,7220,3.0,3.0,SURESH KISHANLAL MUNDRA,JYOTI STRUCTURES LTD,750.000,2.940000e+01,22050.00,13462.50,28666458.87,...,NaN,1900-01-01,17.95,-7987.50,0.05,-4.530036,11.880596,Construction & Engineering,NaN,NaN
30,2539,3.0,3.0,SURESH KISHANLAL MUNDRA,MILLENNIUM ONLINE SOLUTIONS (INDIA) LTD,140.000,7.000000e-01,98.00,288.40,28666458.87,...,NaN,1900-01-01,2.06,190.40,0.00,-4.530036,11.880596,Finance,NaN,NaN
31,7782,3.0,3.0,SURESH KISHANLAL MUNDRA,UTI MASTER SHARES 86 DIVIDEND,2.000,1.000000e+01,20.00,20.00,28666458.87,...,NaN,1900-01-01,10.00,0.00,0.00,-4.530036,11.880596,Others,NaN,NaN
32,30729,3.0,95.0,SURESH KISHANLAL MUNDRA,Axis Arbitrage Reg-IDCW,0.016,1.062500e+01,0.17,0.17,28666458.87,...,9.103577e+10,1900-01-01,10.63,0.02,0.00,0.000000,0.000000,Hybrid: Arbitrage,Axis Mutual Fund,NaN
33,10585,3.0,3.0,SURESH KISHANLAL MUNDRA,Axis Long Term Equity-G,1127.315,4.435320e+01,50000.00,69580.81,28666458.87,...,9.103603e+10,1900-01-01,61.72,19580.81,0.24,0.000000,0.000000,Equity: ELSS,Axis Mutual Fund,NaN
34,10585,3.0,95.0,SURESH KISHANLAL MUNDRA,Axis Long Term Equity-G,8309.520,4.212040e+01,350000.00,512885.18,28666458.87,...,9.103577e+10,1900-01-01,61.72,162885.18,1.79,0.000000,0.000000,Equity: ELSS,Axis Mutual Fund,NaN
35,62193,3.0,3.0,SURESH KISHANLAL MUNDRA,Nippon India Equity Hybrid Fund - Segregated P...,7350.003,5.180000e-02,380.73,380.73,28666458.87,...,4.882324e+11,1900-01-01,0.05,0.00,0.00,0.000000,0.000000,Hybrid: Aggressive Hybrid,Nippon India Mutual Fund,NaN

In [5]:
df.to_excel('demo_36r1h.xlsx')

In [6]:
dfe = pd.read_excel('cent.xlsx')

In [7]:
dfe

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Report Generated on: 26 July 2022,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Capital Gains Report,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
5,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
6,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
7,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
8,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
9,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
10,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
11,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
12,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
13,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
14,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
15,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
16,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
17,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
18,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
19,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
20,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
21,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
22,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
23,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
24,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
25,NaN,ABC,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0

In [8]:
dfe.to_csv('cent.csv')

In [9]:
dfec = pd.read_csv('cent.csv')

In [10]:
dfec.to_excel('csexcent.xlsx')

In [11]:
dfe.to_excel('xlt.xlsx', index=False)

In [14]:
df = pd.read_excel('cent.xlsx',header=None)

In [13]:
df.to_excel('xlt.xlsx', index=False,header=False)